In [43]:
import numpy as np
import itertools

X, Y = [], []

ts = [2,3,84,5,1,54,2,45,34,78]
lag = 3

if len(ts) - lag <= 0:
    X.append(ts)
else:
    for i in range(len(ts) - lag):
        Y.append(ts[i + lag])
        # Substacted 96 for not knowing the day before
        #ab = list(itertools.chain(ts[i:(i + lag)], [2,3]))
        #X.append(ab)
        X.append(ts[i:(i + lag)])
    
#X = list(X)
X, Y = np.array(X), np.array(Y)

# Reshaping the X array to an LSTM input shape 
X = np.reshape(X, (1, X.shape[0], X.shape[1]))

In [16]:
import pandas as pd
df_cons = pd.read_csv('./Consumption_15min.csv')
df_temp = pd.read_csv('./Temp_15min.csv')

In [17]:
df_cons.shape

(177792, 2)

In [18]:
df_temp.shape

(177792, 2)

In [9]:
df_cons

Datetime  Valeur
0       2014-12-06 00:00:00    7.14
1       2014-12-06 00:15:00    7.56
2       2014-12-06 00:30:00    6.72
3       2014-12-06 00:45:00    6.93
4       2014-12-06 01:00:00    7.14
...                     ...     ...
177787  2019-12-31 22:45:00    3.78
177788  2019-12-31 23:00:00    3.99
177789  2019-12-31 23:15:00    3.78
177790  2019-12-31 23:30:00    3.78
177791  2019-12-31 23:45:00    3.78

[177792 rows x 2 columns]

In [10]:
df_temp

time  Temperatures (°C)
0       2014-12-06 00:00:00           4.265863
1       2014-12-06 00:15:00           4.265863
2       2014-12-06 00:30:00           4.265863
3       2014-12-06 00:45:00           4.265863
4       2014-12-06 01:00:00           4.289362
...                     ...                ...
177784  2019-12-31 22:00:00           3.519647
177785  2019-12-31 22:15:00           3.519647
177786  2019-12-31 22:30:00           3.519647
177787  2019-12-31 22:45:00           3.519647
177788  2019-12-31 23:00:00           2.955377

[177789 rows x 2 columns]

In [44]:
print(X.shape)

(1, 7, 3)


In [42]:
print(X)

[[ 2  3 84]
 [ 3 84  5]
 [84  5  1]
 [ 5  1 54]
 [ 1 54  2]
 [54  2 45]
 [ 2 45 34]]
